server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO #id自增
  configuration:
    map-underscore-to-camel-case: true #开启驼峰功能
    auto-mapping-behavior: FULL #自动映射任何复杂的结果
  mapper-locations: classpath:/mybatis/mapper/*.xml

#商品详情图片存储地址
goodsDetailsImageFilePath: E://data/mall/images/goods/details/
#商品卡片图片存储地址
cardImageFilePath: E://data/mall/images/goods/card/
#商品卡片图片存储地址
goodsDetailsSwiperImageFilePath: E://data/mall/images/goods/swiper/